version: '3'

services:
  'react-hooks-auth0-web':
    environment:
      REACT_APP_EXAMPLE_API: 'http://localhost:3005/api/data'
      REACT_APP_AUTH0_DOMAIN: 'mysite.auth0.com'
      REACT_APP_AUTH0_CLIENT_ID: 'some-long-string'
      REACT_APP_AUTH0_REDIRECT_URL: 'http://localhost:3000/'
      REACT_APP_AUTH0_LOGOUT_URL: 'http://localhost:3000/'
      REACT_APP_AUTH0_AUDIENCE: 'https://tvmoviesapi'

  'react-hooks-auth0-api':
    environment:
      PORT: '3005'
      AUTH0_DOMAIN: 'mysite.auth0.com'
      AUTH0_AUDIENCE: 'https://tvmoviesapi'
