version: '3'

services:
  'react-hooks-auth0-web':
    environment:
      AUTH0_DOMAIN: 'mysite.auth0.com'
      AUTH0_CLIENT_ID: 'some-long-string'
      AUTH0_REDIRECT_URL: 'https://mywebsite.com/'
      AUTH0_LOGOUT_URL: 'https://mywebsite.com/'
      AUTH0_AUDIENCE: 'https://tvmoviesapi'

  'react-hooks-auth0-api':
    environment:
      PORT: '3005'
      AUTH0_DOMAIN: 'mysite.auth0.com'
      AUTH0_AUDIENCE: 'https://tvmoviesapi'
